# Generated by Django 3.2.15 on 2022-09-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bike_mass', models.FloatField()),
                ('rider_other', models.FloatField(null=True)),
                ('total_mass', models.FloatField()),
                ('CP_FTP', models.FloatField()),
                ('W_prime', models.FloatField()),
            ],
        ),
    ]
