# Generated by Django 3.2.15 on 2022-10-24 02:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bike_mass', models.FloatField()),
                ('rider_mass', models.FloatField(null=True)),
                ('other_mass', models.FloatField(null=True)),
                ('total_mass', models.FloatField()),
                ('CP_FTP', models.FloatField()),
                ('W_prime', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('lat', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('long', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('ele', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('distance', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('bearing', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('slope', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('segment', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('roughness', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='StaticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_rider', models.FloatField()),
                ('mass_bike', models.FloatField()),
                ('mass_other', models.FloatField()),
                ('delta_kg', models.FloatField(default=0)),
                ('crr', models.FloatField()),
                ('mechanical_efficiency', models.FloatField()),
                ('mol_whl_front', models.FloatField()),
                ('mol_whl_rear', models.FloatField()),
                ('wheel_radius', models.FloatField()),
                ('cp', models.FloatField()),
                ('w_prime', models.FloatField()),
                ('w_prime_recovery_function', models.FloatField()),
                ('below_steady_state_max_slope', models.FloatField()),
                ('below_steady_state_power_usage', models.FloatField()),
                ('over_threshold_min_slope', models.FloatField()),
                ('over_threshold_power_usage', models.FloatField()),
                ('steady_state_power_usage', models.FloatField()),
                ('climbing_cda_increment', models.FloatField()),
                ('climbing_min_slope', models.FloatField()),
                ('descending_cda_increment', models.FloatField()),
                ('descending_max_slope', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('wind_speed_mps', models.FloatField()),
                ('wind_density', models.FloatField()),
                ('timestep_size', models.FloatField()),
                ('starting_distance', models.FloatField()),
                ('starting_speed', models.FloatField()),
                ('delta_cda', models.FloatField(default=0)),
                ('delta_watts', models.FloatField(default=-20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.dynamicmodel')),
                ('static_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.staticmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField()),
                ('min_slope_threshold', models.FloatField(blank=True, default=0)),
                ('max_slope_threshold', models.FloatField(blank=True, default=0)),
                ('gps_geo_json', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.dynamicmodel')),
            ],
        ),
    ]
