# Generated by Django 3.2.15 on 2022-09-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikePlusRiderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_rider', models.FloatField()),
                ('mass_bike', models.FloatField()),
                ('mass_other', models.FloatField()),
                ('crr', models.FloatField()),
                ('mechanical_efficiency', models.FloatField()),
                ('mol_whl_front', models.FloatField()),
                ('mol_whl_rear', models.FloatField()),
                ('wheel_radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.FloatField()),
                ('w_prime', models.FloatField()),
                ('w_prime_recovery_function', models.FloatField()),
                ('below_steady_state_max_slope', models.FloatField()),
                ('below_steady_state_power_usage', models.FloatField()),
                ('over_threshold_min_slope', models.FloatField()),
                ('over_threshold_power_usage', models.FloatField()),
                ('steady_state_power_usage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_direction', models.FloatField()),
                ('wind_speed_mps', models.FloatField()),
                ('wind_density', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climbing_cda_increment', models.FloatField()),
                ('climbing_min_slope', models.FloatField()),
                ('descending_cda_increment', models.FloatField()),
                ('descending_max_slope', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestep_size', models.FloatField()),
                ('starting_distance', models.FloatField()),
                ('starting_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_plus_rider_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bikeplusridermodel')),
                ('cp_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cpmodel')),
                ('environment_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.environmentmodel')),
                ('position_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.positionmodel')),
                ('technical_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.technicalmodel')),
            ],
        ),
    ]
