# Generated by Django 3.2.15 on 2022-09-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='rider_other',
            new_name='other_mass',
        ),
        migrations.AddField(
            model_name='athlete',
            name='rider_mass',
            field=models.FloatField(null=True),
        ),
    ]
